version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # backend:
  #   build: ./backend
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mysql
  #   environment:
  #     DB_HOST: mysql
  #     DB_USER: root
  #     DB_PASSWORD: root
  #     DB_NAME: expense_db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  mysql_data:
